apiVersion: garden.io/v1
kind: Project
name: vote-demo-quickstart
defaultEnvironment: ephemeral
dotIgnoreFile: .gitignore

variables:
  postgresUsername: postgres
  postgresDatabase: postgres
  postgresPassword: postgres

  # Replace underscores as Kubernetes namespaces do not allow them.
  userNamespace: vote-demo-quickstart-${kebabCase(local.username)}

environments:
  - name: local
    defaultNamespace: ${var.userNamespace}
    variables:
      baseHostname: local.demo.garden
  - name: remote
    defaultNamespace: ${var.userNamespace}
    variables:
      baseHostname: "<add you values here>"
      imagePullSecretName: "<add you values here>"
  - name: ephemeral

providers:
  - name: local-kubernetes
    environments: [local]
    namespace: ${environment.namespace}
    defaultHostname: ${var.baseHostname}
  - name: ephemeral-kubernetes
    environments: [ephemeral]

  # You can use Garden with your own remote Kubernetes clusters as well.
  # Please see our docs to learn how to configure the values below: https://docs.garden.io/kubernetes-plugins/remote-k8s
  - name: kubernetes
    environments: [remote]
    context: "<add your values>"
    ingressClass: "nginx"
    buildMode: cluster-buildkit
    imagePullSecrets:
      - name: ${var.imagePullSecretName}
        namespace: default
    deploymentRegistry:
      hostname: "<add your values>"
      namespace: "<add your values>"
    namespace: ${environment.namespace}
    defaultHostname: ${var.baseHostname}

